<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Modules.Ai.Application\Modules.Ai.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.9.0-beta.1" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Microsoft.Agents.AI" Version="1.13.0" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.13.0" />
    <PackageReference Include="Microsoft.Agents.AI.Workflows" Version="1.13.0" />
  </ItemGroup>
</Project>
