// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Identity.Infrastructure.Api.IdentityApi.GetUserAsync(System.Guid,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Modules.Identity.Api.IdentityUserSnapshot}")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Identity.Infrastructure.Api.IdentityApi.ListUsersAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.IReadOnlyList{Modules.Identity.Api.IdentityUserSnapshot}}")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Identity.Infrastructure.Repositories.RefreshTokenRepository.AddAsync(Modules.Identity.Domain.RefreshTokens.RefreshToken,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Identity.Infrastructure.Repositories.RefreshTokenRepository.GetByHashAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Modules.Identity.Domain.RefreshTokens.RefreshToken}")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Identity.Infrastructure.Repositories.UserRepository.AddAsync(Modules.Identity.Domain.Users.User,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Identity.Infrastructure.Repositories.UserRepository.CountAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Identity.Infrastructure.Repositories.UserRepository.GetByEmailAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Modules.Identity.Domain.Users.User}")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Identity.Infrastructure.Repositories.UserRepository.GetByIdAsync(System.Guid,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Modules.Identity.Domain.Users.User}")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Identity.Infrastructure.Repositories.UserRepository.ListAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.IReadOnlyList{Modules.Identity.Domain.Users.User}}")]
