// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Network.Infrastructure.Api.NetworkApi.GetByCodeAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Modules.Network.Api.TowerSnapshot}")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Network.Infrastructure.Api.NetworkApi.GetRegionHealthAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.IReadOnlyList{Modules.Network.Api.RegionHealth}}")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Network.Infrastructure.Api.NetworkApi.ListByRegionAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.IReadOnlyList{Modules.Network.Api.TowerSnapshot}}")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Network.Infrastructure.Api.NetworkApi.ListTowersAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.IReadOnlyList{Modules.Network.Api.TowerSnapshot}}")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Network.Infrastructure.Repositories.TowerRepository.AddRangeAsync(System.Collections.Generic.IEnumerable{Modules.Network.Domain.Towers.Tower},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Network.Infrastructure.Repositories.TowerRepository.CountAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Network.Infrastructure.Repositories.TowerRepository.GetByCodeAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Modules.Network.Domain.Towers.Tower}")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Network.Infrastructure.Repositories.TowerRepository.ListAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.IReadOnlyList{Modules.Network.Domain.Towers.Tower}}")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Network.Infrastructure.Repositories.TowerRepository.ListByRegionAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.IReadOnlyList{Modules.Network.Domain.Towers.Tower}}")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Modules.Network.Infrastructure.Repositories.TowerRepository.SaveChangesAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
