<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="CsvHelper" Version="33.0.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Modules.Network.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Application\Application.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Modules.Network.Api\Modules.Network.Api.csproj" />
    <ProjectReference Include="..\Modules.Network.Application\Modules.Network.Application.csproj" />
  </ItemGroup>

</Project>
